const KEY_SIZE = 32
const TAG_SIZE = 16

const LENGTH_OR_END_PLAINTEXT = 2
const LENGTH_OR_END_CIPHERTEXT = LENGTH_OR_END_PLAINTEXT + TAG_SIZE

module.exports = {
  KEY_SIZE,
  TAG_SIZE,
  LENGTH_OR_END_PLAINTEXT,
  LENGTH_OR_END_CIPHERTEXT,
}
